######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:

  # name - appears as the title - REQUIRED
  name: '&0Vida'

  # rows - the number of rows of the chest - REQUIRED
  rows: 4

  # command - OPTIONAL (you can remove this or set it to '')
  command: ''
  
  # permissionView - MATERIAL NAME - DATA
  permissionView:
    ICON-VIEW: true
    ICON-ITEM: 397
    DATA-VALUE: 3
    SKULL-OWNER: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmViNTg4YjIxYTZmOThhZDFmZjRlMDg1YzU1MmRjYjA1MGVmYzljYWI0MjdmNDYwNDhmMThmYzgwMzQ3NWY3In19fQ=='
    DESCRIPTION:
      - ''
      - ' &a▸ &fNo tienes permiso'
      - ''
  ######################
  #+                  +#
  #       ITEMS        #
  #+                  +#
  ######################

10heart:
  ACTION: 'vote:%heart10%'
  NAME: '&410 ❤ de vida'
  DESCRIPTION:
    - ' &a▸ &7Durante el juego'
    - ' &a▸ &7los jugadores tendran'
    - ' &a▸ &710 ❤ de vida'
    - ''
    - ' &a▸ &fVotos: &a%sw_arena_vote_heart_normal%'
    - ''
    - ' &a▸ &aClick para votar'
  ICON-ITEM: 397
  DATA-VALUE: 3
  SKULL-OWNER: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTZjMTVmYjRlOWEzMTE5MWYwY2I0ZGE1NmZlNjAzMzRkZDQ2ZWIzYTU4MjExMWI0ZjhmMjdlZGRiNzYwZTJjIn19fQ=='
  PERMISSION: vote.heart.10
  POSITION-X: 3
  POSITION-Y: 2
20heart:
  ACTION: 'vote:%heart20%'
  NAME: '&420 ❤ de vida'
  DESCRIPTION:
    - ' &a▸ &7Durante el juego'
    - ' &a▸ &7los jugadores tendran'
    - ' &a▸ &720 ❤ de vida'
    - ''
    - ' &a▸ &fVotos: &a%sw_arena_vote_heart_double%'
    - ''
    - ' &a▸ &aClick para votar'
  ICON-ITEM: 397
  DATA-VALUE: 3
  SKULL-OWNER: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzVlMmUwOTU5NzEyZGNkMzM1N2NjM2NlYTg1Zjk5YjNmZDgwOTc4NTVjNzU0YjliMTcxZjk2MzUxNDIyNWQifX19'
  PERMISSION: vote.heart.20
  POSITION-X: 5
  POSITION-Y: 2
30heart:
  ACTION: 'vote:%heart30%'
  NAME: '&430 ❤ de vida'
  DESCRIPTION:
    - ' &a▸ &7Durante el juego'
    - ' &a▸ &7los jugadores tendran'
    - ' &a▸ &730 ❤ de vida'
    - ''
    - ' &a▸ &fVotes: &a%sw_arena_vote_heart_triple%'
    - ''
    - ' &a▸ &aClick para votar'
  ICON-ITEM: 397
  DATA-VALUE: 3
  SKULL-OWNER: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjI4NjhlYzZkYmRiYjZiZWNmNjk4ZGExMzZlN2E2Y2QyOGUxOTMxNDc5NmNlMjZhM2Y2N2Q2YWI2NTZlYjIxOSJ9fX0='
  PERMISSION: vote.heart.30
  POSITION-X: 7
  POSITION-Y: 2
Back:
  ACTION: 'open: vote.yml'
  NAME: '&cVolver'
  DESCRIPTION:
    - ' &a▸ &7Vuelve al menu'
    - ' &a▸ &7de votacion'
    - ''
    - ' &a▸ &aClick para volver'
  ICON-ITEM: 397
  DATA-VALUE: 3
  SKULL-OWNER: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmUzZjUwYmE2MmNiZGEzZWNmNTQ3OWI2MmZlZGViZDYxZDc2NTg5NzcxY2MxOTI4NmJmMjc0NWNkNzFlNDdjNiJ9fX0='
  POSITION-X: 5
  POSITION-Y: 4