######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:

  # name - appears as the title - REQUIRED
  name: '&0Cofres'

  # rows - the number of rows of the chest - REQUIRED
  rows: 4

  # command - OPTIONAL (you can remove this or set it to '')
  command: ''
  
  # permissionView - MATERIAL NAME - DATA
  permissionView:
    ICON-VIEW: true
    ICON-ITEM: 397
    DATA-VALUE: 3
    SKULL-OWNER: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmViNTg4YjIxYTZmOThhZDFmZjRlMDg1YzU1MmRjYjA1MGVmYzljYWI0MjdmNDYwNDhmMThmYzgwMzQ3NWY3In19fQ=='
    DESCRIPTION:
      - ''
      - ' &a▸ &fNo tienes permiso'
      - ''
  ######################
  #+                  +#
  #       ITEMS        #
  #+                  +#
  ######################
basic:
  ACTION: 'vote:%basic%'
  NAME: '&bCofres basicos'
  DESCRIPTION:
    - ' &a▸ &7Durante el juego'
    - ' &a▸ &7los cofres tendran'
    - ' &a▸ &7items basicos'
    - ''
    - ' &a▸ &fVotos: &a%sw_arena_vote_chest_basic%'
    - ''
    - ' &a▸ &aClick para votar'
  ICON-ITEM: 397
  DATA-VALUE: 3
  SKULL-OWNER: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGNkM2M0NWQ3YjgzODRlOGExOTYzZTRkYTBhZTZiMmRhZWIyYTNlOTdhYzdhMjhmOWViM2QzOTU5NzI1Nzk5ZiJ9fX0='
  PERMISSION: vote.chest.basic
  POSITION-X: 3
  POSITION-Y: 2
normal:
  ACTION: 'vote:%normal%'
  NAME: '&aCofres normales'
  DESCRIPTION:
    - ' &a▸ &7Durante el juego'
    - ' &a▸ &7los cofres tendran'
    - ' &a▸ &7items normales'
    - ''
    - ' &a▸ &fVotos: &a%sw_arena_vote_chest_normal%'
    - ''
    - ' &a▸ &aClick para votar'
  ICON-ITEM: 397
  DATA-VALUE: 3
  SKULL-OWNER: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmFlNGJlM2ZjNzg1ZjZjN2NjNzc3YzkzN2Y1YWRlOGZlOGQ3MWY2ZGZhNDhkYTg4ODllOThhZjA3NTI1ZmVmZiJ9fX0='
  PERMISSION: vote.chest.normal
  POSITION-X: 5
  POSITION-Y: 2
op:
  ACTION: 'vote:%op%'
  NAME: '&cCofres op'
  DESCRIPTION:
    - ' &a▸ &7Durante el juego'
    - ' &a▸ &7los cofres tendran'
    - ' &a▸ &7items op'
    - ''
    - ' &a▸ &fVotes: &a%sw_arena_vote_chest_op%'
    - ''
    - ' &a▸ &aClick para votar'
  ICON-ITEM: 397
  DATA-VALUE: 3
  SKULL-OWNER: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjYyNGM5MjdjZmVhMzEzNTU0Mjc5OTNkOGI3OTcxMmU4NmY5NGQ1OTUzNDMzZjg0ODg0OWEzOWE2ODc5In19fQ=='
  PERMISSION: vote.chest.op
  POSITION-X: 7
  POSITION-Y: 2
Back:
  ACTION: 'open: vote.yml'
  NAME: '&cVolver'
  DESCRIPTION:
    - ' &a▸ &7Vuelve al menu'
    - ' &a▸ &7de votacion'
    - ''
    - ' &a▸ &aClick para volver'
  ICON-ITEM: 397
  DATA-VALUE: 3
  SKULL-OWNER: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmUzZjUwYmE2MmNiZGEzZWNmNTQ3OWI2MmZlZGViZDYxZDc2NTg5NzcxY2MxOTI4NmJmMjc0NWNkNzFlNDdjNiJ9fX0='
  POSITION-X: 5
  POSITION-Y: 4