name: SkyWars
version: ${project.version}
main: com.dazzhub.skywars.Main
api-version: 1.13
authors: [DazzHub]
commands:
  skywars:
    aliases: ['sw', 'dw']
  join:
  leave:
    aliases: ['quit', 'salir']
  party:
    aliases: ['p']