MySQL:
  enabled: false
  hostname: "127.0.0.1"
  port: 3306
  database: "SkyWars"
  username: "root"
  password: ""
#Upon entering, it will show you an update announcement
checkVersion: false
#Join player save dates in mysql/sql
Default:
  Kit:
    Solo: 'Default'
    Team: 'Default'
  Cage:
    Solo: 'Default'
    Team: 'Default'
  WinEffect:
    Solo: 'fireworks'
    Team: 'fireworks'
  KillEffect:
    Solo: 'none'
    Team: 'none'
  Trail:
    Solo: 'none'
    Team: 'none'
  KillSound:
    Solo: 'BLOCK_NOTE_BLOCK_PLING' #use sounds 1.16
    Team: 'BLOCK_NOTE_BLOCK_PLING'
  Lang: 'en-EN' #Default language en-EN, es-ES
Coins:
  DeathSolo: 8
  DeathTeam: 8

  FirstKillSolo: 30
  FirstKillTeam: 30

  KillSolo: 16
  KillTeam: 16

  WinSolo: 50
  WinTeam: 50
ReTeleportCage: 2
Holograms: