######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:

  # name - appears as the title - REQUIRED
  name: '&0Languages'

  # rows - the number of rows of the chest - REQUIRED
  rows: 3

  # command - OPTIONAL (you can remove this or set it to '')
  command: ''

  # permissionView - MATERIAL NAME - DATA
  permissionView:
    ICON-VIEW: true
    ICON-ITEM: 'SIGN'
    DATA-VALUE: 0
    DESCRIPTION:
      - ''
      - ' &a▸ &fYou currently do not have'
      - ' &a▸ &fpermission to do this'
      - ''
Spanish:
  ACTION: 'lang: es-ES'
  NAME: '&aEspañol'
  DESCRIPTION:
    - '&a▸ &7Cambia el idioma a español'
    - '&a▸ &7de todo el skywars'
    - ''
    - '&a▸ &7Click para cambiar idioma'
  ICON-ITEM: 397
  DATA-VALUE: 3
  SKULL-OWNER: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGE5MDAzMzliYjk3MWYwMjhhZmU2NzI0YTg1MjE5YmEyMzM5OTE4YmE0OWMxMTlkMmZiODcxZTQ3YWM5OWIzOSJ9fX0='
  POSITION-X: 2
  POSITION-Y: 2
English:
  ACTION: 'lang: en-EN'
  NAME: '&eEnglish'
  DESCRIPTION:
    - '&a▸ &7Change the language to English'
    - '&a▸ &7of all the skywars'
    - ''
    - '&a▸ &7Click to change language'
  ICON-ITEM: 397
  DATA-VALUE: 3
  SKULL-OWNER: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODM3ZmM4NDFhZDIwNjA4ZTc2MWQ0MTMxOTEyM2NkYjU1ODU2YTBlYmMzODA0NzAzODU2ZTVkODZhMTM1MzQ1In19fQ=='
  POSITION-X: 3
  POSITION-Y: 2
close:
  ACTION: 'close'
  NAME: '&cClose'
  DESCRIPTION:
    - ''
  ICON-ITEM: 368
  DATA-VALUE: 0
  POSITION-X: 5
  POSITION-Y: 3