######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:

  # name - appears as the title - REQUIRED
  name: '&8➣ Shop menu'

  # rows - the number of rows of the chest - REQUIRED
  rows: 6

  # command - OPTIONAL (you can remove this or set it to '')
  command: 'shop'

  # permissionView - MATERIAL NAME - DATA
  permissionView:
    ICON-ITEM: 'SIGN'
    DATA-VALUE: 0
    DESCRIPTION:
      - ''
      - '&8» &eYou currently don''t have'
      - '&8» &6permission to do this'
      - ''
cagesolo:
  ACTION: 'open: cage-solo.yml'
  NAME: '&e&lcagesolo'
  DESCRIPTION:
    - '&7➲ &2&lCLICK&f to buy cages'
  ICON-ITEM: 20
  DATA-VALUE: 0
  POSITION-X: 1
  POSITION-Y: 2
cageteam:
  ACTION: 'open: cage-team.yml'
  NAME: '&e&lcageteam'
  DESCRIPTION:
    - '&7➲ &2&lCLICK&f to buy cages'
  ICON-ITEM: 20
  DATA-VALUE: 0
  POSITION-X: 2
  POSITION-Y: 2
kitsolo:
  ACTION: 'open: kit-solo.yml'
  NAME: '&e&lkitsolo'
  DESCRIPTION:
    - '&7➲ &2&lCLICK&f to buy cages'
  ICON-ITEM: 261
  DATA-VALUE: 0
  POSITION-X: 4
  POSITION-Y: 2
kitteam:
  ACTION: 'open: kit-team.yml'
  NAME: '&e&lkitteam'
  DESCRIPTION:
    - '&7➲ &2&lCLICK&f to buy cages'
  ICON-ITEM: 261
  DATA-VALUE: 0
  POSITION-X: 5
  POSITION-Y: 2
killeffectsolo:
  ACTION: 'open: killeffect-solo.yml'
  NAME: '&e&lkilleffectsolo'
  DESCRIPTION:
    - '&7➲ &2&lCLICK&f to buy cages'
  ICON-ITEM: 261
  DATA-VALUE: 0
  POSITION-X: 7
  POSITION-Y: 2
killeffectteam:
  ACTION: 'open: killeffect-team.yml'
  NAME: '&e&lkilleffectteam'
  DESCRIPTION:
    - '&7➲ &2&lCLICK&f to buy cages'
  ICON-ITEM: 261
  DATA-VALUE: 0
  POSITION-X: 8
  POSITION-Y: 2
traileffectsolo:
  ACTION: 'open: traileffect-solo.yml'
  NAME: '&e&ltraileffectsolo'
  DESCRIPTION:
    - '&7➲ &2&lCLICK&f to buy cages'
  ICON-ITEM: 261
  DATA-VALUE: 0
  POSITION-X: 1
  POSITION-Y: 3
trailffectteam:
  ACTION: 'open: traileffect-team.yml'
  NAME: '&e&ltrailffectteam'
  DESCRIPTION:
    - '&7➲ &2&lCLICK&f to buy cages'
  ICON-ITEM: 261
  DATA-VALUE: 0
  POSITION-X: 2
  POSITION-Y: 3
wineffectsolo:
  ACTION: 'open: wineffect-solo.yml'
  NAME: '&e&lwineffectsolo'
  DESCRIPTION:
    - '&7➲ &2&lCLICK&f to buy cages'
  ICON-ITEM: 261
  DATA-VALUE: 0
  POSITION-X: 4
  POSITION-Y: 3
winffectteam:
  ACTION: 'open: wineffect-team.yml'
  NAME: '&e&lwinffectteam'
  DESCRIPTION:
    - '&7➲ &2&lCLICK&f to buy cages'
  ICON-ITEM: 261
  DATA-VALUE: 0
  POSITION-X: 5
  POSITION-Y: 3
close:
  ACTION: 'close'
  NAME: '&cClose'
  DESCRIPTION:
    - ''
  ICON-ITEM: 368
  DATA-VALUE: 0
  POSITION-X: 5
  POSITION-Y: 5

