######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:

  # name - appears as the title - REQUIRED
  name: '&0Shop'

  # rows - the number of rows of the chest - REQUIRED
  rows: 6

  # command - OPTIONAL (you can remove this or set it to '')
  command: 'shop'

  # permissionView - MATERIAL NAME - DATA
  permissionView:
    ICON-VIEW: true
    ICON-ITEM: 'SIGN'
    DATA-VALUE: 0
    DESCRIPTION:
      - ''
      - ' &a▸ &fYou currently do not have'
      - ' &a▸ &fpermission to do this'
      - ''
shopsolo:
  ACTION: 'open: shop-solo.yml'
  NAME: '&eShop solo'
  DESCRIPTION:
    - '&7Open the kit shop, cages'
    - '&7and other things for games'
    - '&7solo'
    - ''
    - '&aClick to open'
  ICON-ITEM: 322
  DATA-VALUE: 0
  POSITION-X: 3
  POSITION-Y: 3
shopteam:
  ACTION: 'open: shop-team.yml'
  NAME: '&dShop team'
  DESCRIPTION:
    - '&7Open the kit shop, cages'
    - '&7and other things for games'
    - '&7team'
    - ''
    - '&aClick to open'
  ICON-ITEM: 354
  DATA-VALUE: 0
  POSITION-X: 5
  POSITION-Y: 3
shopranked:
  ACTION: 'open: shop-ranked.yml'
  NAME: '&dShop ranked'
  DESCRIPTION:
    - '&7Open the kit shop, cages'
    - '&7and other things for games'
    - '&7ranked'
    - ''
    - '&aClick to open'
  ICON-ITEM: 'DIAMOND_SWORD'
  DATA-VALUE: 0
  POSITION-X: 7
  POSITION-Y: 3  
Cerrar:
  ACTION: 'close'
  NAME: '&cCerrar'
  DESCRIPTION:
    - ''
  ICON-ITEM: 368
  DATA-VALUE: 0
  POSITION-X: 5
  POSITION-Y: 5