######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:

  # name - appears as the title - REQUIRED
  name: '&8➣ Win Effects team #1'

  # rows - the number of rows of the chest - REQUIRED
  rows: 5
  
  # command - OPTIONAL (you can remove this or set it to '')
  command: ''
  
  # permissionView - MATERIAL NAME - DATA
  permissionView:
    ICON-ITEM: 'SIGN'
    DATA-VALUE: 0
    DESCRIPTION:
      - ''
      - '&8» &eYou currently don''t have'
      - '&8» &6permission to do this'
      - ''
antigravity:
  PRICE: 0
  ACTION: 'wineffect: antigravity/TEAM'
  NAME: '&eantigravity'
  DESCRIPTION:
    - ''
    - '&7➲ &e&l%name%'
    - '&7➲ &2&lCLICK&f to buy effect %price%'
    - ''
  DESCRIPTION-PURCHASED:
    - ''
    - '&7➲ &eOBTAINED'
    - ''
  DESCRIPTION-SELECTED:
    - ''
    - '&7➲ &eSELECTED'
    - ''
  ICON-ITEM: 298
  DATA-VALUE: 0
  POSITION-X: 2
  POSITION-Y: 2